package com.itama.firma_documental;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class document_signers implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DOCUMENT_SIGNERS_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "DOCUMENT_SIGNERS_ID_SEQ", name = "DOCUMENT_SIGNERS_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Identificador del documento")
	private java.lang.String documentId;

	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label("Identificador Usuario")
	private java.util.List<java.lang.String> signerId;

	@org.kie.api.definition.type.Label(value = "Tipo de documento")
	private java.lang.String tipoDocumento;

	public document_signers() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(java.lang.String documentId) {
		this.documentId = documentId;
	}

	public java.util.List<java.lang.String> getSignerId() {
		return this.signerId;
	}

	public void setSignerId(java.util.List<java.lang.String> signerId) {
		this.signerId = signerId;
	}

	public java.lang.String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(java.lang.String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public document_signers(java.lang.Long id, java.lang.String documentId,
			java.util.List<java.lang.String> signerId,
			java.lang.String tipoDocumento) {
		this.id = id;
		this.documentId = documentId;
		this.signerId = signerId;
		this.tipoDocumento = tipoDocumento;
	}

}