package com.itama.firma_documental;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class tramite_firma implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TRAMITE_FIRMA_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "TRAMITE_FIRMA_ID_SEQ", name = "TRAMITE_FIRMA_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Documentos")
	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private java.util.List<com.itama.firma_documental.document_signers> documents;

	@org.kie.api.definition.type.Label("Nro Expediente")
	private java.lang.String idExpediente;

	@org.kie.api.definition.type.Label("Fecha de creación")
	private java.time.LocalDateTime fechaCreacion;

	@org.kie.api.definition.type.Label("responsable")
	private java.lang.String responsable;

	public tramite_firma() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.util.List<com.itama.firma_documental.document_signers> getDocuments() {
		return this.documents;
	}

	public void setDocuments(
			java.util.List<com.itama.firma_documental.document_signers> documents) {
		this.documents = documents;
	}

	public java.lang.String getIdExpediente() {
		return this.idExpediente;
	}

	public void setIdExpediente(java.lang.String idExpediente) {
		this.idExpediente = idExpediente;
	}

	public java.time.LocalDateTime getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(java.time.LocalDateTime fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public java.lang.String getResponsable() {
		return this.responsable;
	}

	public void setResponsable(java.lang.String responsable) {
		this.responsable = responsable;
	}

	public tramite_firma(
			java.lang.Long id,
			java.util.List<com.itama.firma_documental.document_signers> documents,
			java.lang.String idExpediente,
			java.time.LocalDateTime fechaCreacion, java.lang.String responsable) {
		this.id = id;
		this.documents = documents;
		this.idExpediente = idExpediente;
		this.fechaCreacion = fechaCreacion;
		this.responsable = responsable;
	}

}